module.exports = {
  model: {
    user: {
      defaultUserRole: 'user',
      statusEnum: ['active', 'inactive'],
      defaultStatus: 'active',
      socialLoginTypeEnum: ['facebook', 'google', 'apple'],
      typeOfAccountEnum: ['email', 'apple', 'google', 'facebook'],
      defaultTypeOfAccount: 'email',
      connectionTypeEnum: ['shopify', 'wix', 'woocommerce', 'squarespace'],
    },
    customer: {
      genderEnum: {
        MALE: 'MALE',
        FEMALE: 'FEMALE',
        NON_BINARY: 'NON_BINARY',
        TO_BE_CONFIRMED: 'TO_BE_CONFIRMED',
      },
      mailPreferencesEnum: [
        { value: 'discountsAndSales', id: 'R8VYjc', isSelected: true },
        { value: 'bndleAndPartners', id: 'QYgHEL', isSelected: true },
        { value: 'exclusives', id: 'U5kWBn', isSelected: true },
        { value: 'newStuff', id: 'WeU7Gi', isSelected: true },
      ],
      socialChannels: ['FACEBOOK', 'GOOGLE', 'EMAIL'],
      // 'bndleAndPartners', 'exclusives', 'newStuff'],
    },
    product: {
      productSourceEnum: ['direct', 'shopify', 'wix', 'woocommerce', 'squarespace'],
      statusproductEnum: ['active', 'inactive', 'publish', 'unpublish'],
      STATUS: ['PUBLISHED', 'UNPUBLISHED', 'ENABLED', 'DISABLED', 'REJECTED', 'IMPORTED'],
      venderStatus: ['ENABLED', 'DISABLED'],
      SPECIAL_TAGS: {
        feature: 'FEATURE',
        bestSeller: 'BEST_SELLER',
        hot: 'HOT',
        newArrival: 'NEW_ARRIVALS',
        trending: 'TRENDING',
        sale: 'SALE',
      },
      quantityLimit: 10000,
    },
    order: {
      orderStatus: {
        NEW: 'NEW',
        PARTIALLY_ON_HOLD: 'PARTIALLY_ON_HOLD',
        ON_HOLD: 'ON_HOLD',
        PARTIALLY_REQUEST_DECLINED: 'PARTIALLY_REQUEST_DECLINED',
        REQUEST_DECLINED: 'REQUEST_DECLINED',
        PARTIALLY_SHIPPED: 'PARTIALLY_SHIPPED',
        SHIPPED: 'SHIPPED',
        PARTIALLY_RETURNED: 'PARTIALLY_RETURNED',
        RETURNED: 'RETURNED',
        PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
        REFUNDED: 'REFUNDED',
        PARTIALLY_RETURN_IN_PROGRESS: 'PARTIALLY_RETURN_IN_PROGRESS',
        RETURN_IN_PROGRESS: 'RETURN_IN_PROGRESS',
      },
      vendorOrderStatus: {
        NEW: 'NEW',
        ON_HOLD: 'ON_HOLD',
        REQUEST_DECLINED: 'REQUEST_DECLINED',
        PARTIALLY_ON_HOLD: 'PARTIALLY_ON_HOLD',
        PARTIALLY_SHIPPED: 'PARTIALLY_SHIPPED',
        SHIPPED: 'SHIPPED',
      },
    },
    logger: {
      typeEnum: ['sync', 'publish'],
      levelEnum: ['error', 'warn', 'info', 'verbose', 'debug'],
    },
  },
  config: {
    roles: {
      adminRoles: ['getUsers', 'manageUsers'],
      vendor: ['getUsers'],
    },
  },
  qeueue: {
    default_attempts: 3,
  },
  category: {
    Bathe: {
      'Bath Time': {
        Towels: 'Baby & Toddler, Baby Bathing',
        'Hooded Towels': 'Baby & Toddler, Baby Bathing',
        Robes: 'Baby & Toddler, Baby Bathing',
        Washbags: 'Baby & Toddler, Baby Bathing',
        Cloths: 'Baby & Toddler, Baby Bathing',
        Toys: 'Baby & Toddler, Baby Bathing',
        Accessories: 'Baby & Toddler, Baby Bathing',
      },
      Teeth: {
        Toys: 'Baby & Toddler, Baby Bathing',
        Stools: 'Baby & Toddler, Baby Bathing',
        Toothbrush: 'Baby & Toddler, Baby Bathing',
        Teethers: 'Baby & Toddler, Baby Bathing',
        Toothpaste: 'Baby & Toddler, Baby Bathing',
      },
      'Baby Change': {
        'Training Mats': 'Baby & Toddler, Baby Bathing',
        'Toilet Seats': 'Baby & Toddler, Baby Bathing',
        Potties: 'Baby & Toddler, Potty Training',
        'Changing Mats': 'Baby & Toddler, Baby Bathing',
        'Baby Wipes': 'Baby & Toddler, Diapering',
        Nappies: 'Baby & Toddler, Diapering',
      },
      Cosmetics: {
        'Hair Care': 'Baby & Toddler, Potty Training',
        'Skin Care': 'Baby & Toddler, Potty Training',
        'Nail Care': 'Baby & Toddler, Potty Training',
        Makeup: 'Baby & Toddler, Potty Training',
      },
      'Furry Friends': {
        'Pets Grooming': 'Animals & Pet Supplies',
        Accessories: 'Animals & Pet Supplies',
      },
    },
    Feed: {
      Chairs: {
        'Booster Seating': 'Furniture, Baby & Toddler Furniture',
        'High Chair': 'Furniture, Baby & Toddler Furniture',
        Accessories: 'Furniture, Baby & Toddler Furniture',
        Covers: 'Furniture, Baby & Toddler Furniture',
      },
      Tablewear: {
        Placemats: 'Home & Garden, Kitchen & Dining',
        'Dinner Sets': 'Home & Garden, Kitchen & Dining',
        Cutlery: 'Home & Garden, Kitchen & Dining',
        'Plates & Bowles': 'Baby & Toddler, Nursing & Feeding',
      },
      Accessories: {
        'Dribble Bibs': 'Baby & Toddler, Nursing & Feeding',
      },
      Weaning: {
        Bibs: 'Baby & Toddler, Nursing & Feeding',
        Coveralls: 'Baby & Toddler, Nursing & Feeding',
        Muslins: 'Baby & Toddler, Nursing & Feeding',
        'Splash Mat': 'Baby & Toddler, Nursing & Feeding',
      },
      Food: {
        Subscriptions: 'Baby & Toddler, Nursing & Feeding',
        Baby: 'Baby & Toddler, Nursing & Feeding',
        Toddlers: 'Baby & Toddler, Nursing & Feeding',
      },
      Drinking: {
        'Bottles ': 'Baby & Toddler, Nursing & Feeding',
        Cups: 'Baby & Toddler, Nursing & Feeding',
        Teas: 'Baby & Toddler, Nursing & Feeding',
        'Water Bottles': 'Home & Garden, Kitchen & Dining',
      },
      Storage: {
        Lunchboxes: 'Home & Garden, Kitchen & Dining',
        'Lunch Bags': 'Home & Garden, Kitchen & Dining',
        'Snack Boxes': 'Baby & Toddler, Nursing & Feeding',
      },
      Breastfeeding: {
        Muslins: 'Baby & Toddler, Nursing & Feeding',
        Accessories: 'Baby & Toddler, Nursing & Feeding',
        Muslins: 'Baby & Toddler, Nursing & Feeding',
      },
    },
    Gifts: {
      Accessories: {
        Baking: 'Arts & Entertainment, Party & Celebration',
        Cards: 'Arts & Entertainment, Party & Celebration',
        Christmas: 'Arts & Entertainment, Party & Celebration',
        'Dolls House': 'Arts & Entertainment, Party & Celebration',
        Garlands: 'Arts & Entertainment, Party & Celebration',
        Bunting: 'Arts & Entertainment, Party & Celebration',
        'Gift Wraps': 'Arts & Entertainment, Party & Celebration',
        Party: 'Arts & Entertainment, Party & Celebration',
        'Birthday Candles': 'Arts & Entertainment, Party & Celebration',
        Candles: 'Arts & Entertainment, Party & Celebration',
        'Birthday Boards': 'Arts & Entertainment, Party & Celebration',
        'Cake Topper': 'Arts & Entertainment, Party & Celebration',
        Plaques: 'Arts & Entertainment, Party & Celebration',
        'Milestone Cards': 'Arts & Entertainment, Party & Celebration',
      },
    },
    Home: {
      'Decorative Accessories': {
        Mobiles: 'Baby & Toddler, Baby Toys & Activity Equipment',
        Cushions: 'Home & Garden, Decor',
        Rugs: 'Home & Garden, Decor',
        Lighting: 'Home & Garden, Decor',
        Beanbags: 'Home & Garden, Decor',
        'Beanbag Chairs': 'Home & Garden, Decor',
        'Lounge Chairs': 'Home & Garden, Decor',
        Loungers: 'Home & Garden, Decor',
        Mirrors: 'Home & Garden, Decor',
        Playsets: 'Home & Garden, Decor',
        Curtains: 'Home & Garden, Decor',
      },
      Furniture: {
        Cots: 'Furniture, Baby & Toddler Furniture',
        'Chaning table': 'Furniture, Baby & Toddler Furniture',
        'Beds ': 'Furniture, Baby & Toddler Furniture',
        Wardrobes: 'Furniture, Baby & Toddler Furniture',
        Tables: 'Furniture, Baby & Toddler Furniture',
        Chairs: 'Furniture, Baby & Toddler Furniture',
        Shelves: 'Furniture, Baby & Toddler Furniture',
      },
      Walls: {
        Wallpapers: 'Home & Garden, Decor',
        Stickers: 'Home & Garden, Decor',
        Posters: 'Home & Garden, Decor',
        Prints: 'Home & Garden, Decor',
        'Wall Hangings': 'Home & Garden, Decor',
        'Signs ': 'Home & Garden, Decor',
        Garlands: 'Home & Garden, Decor',
      },
      Storage: {
        Toys: 'Home & Garden, Decor',
        Baskets: 'Home & Garden, Decor',
        Crates: 'Home & Garden, Decor',
        Boxes: 'Home & Garden, Decor',
      },
      Beds: {
        Cots: 'Furniture, Baby & Toddler Furniture',
        Cribs: 'Furniture, Baby & Toddler Furniture',
        'Single Beds': 'Furniture,Beds & Accessories',
        'Double Beds': 'Furniture,Beds & Accessories',
        'Bunk Beds': 'Furniture,Beds & Accessories',
        'Sleep Pods': 'Furniture,Beds & Accessories',
        'Moses Baskets': 'Furniture,Beds & Accessories',
        Cribs: 'Furniture,Beds & Accessories',
        Mattresses: 'Furniture,Beds & Accessories',
        'Mattresses Protector': 'Furniture,Beds & Accessories',
      },
      Tables: {
        'Changing Tables': 'Furniture,Beds & Accessories',
      },
      'Decor & Storage': {
        Wardrobes: 'Furniture,Beds & Accessories',
        Bookcase: 'Furniture,Beds & Accessories',
        Shelves: 'Furniture,Beds & Accessories',
        Rugs: 'Furniture,Beds & Accessories',
      },
      Seating: {
        Tables: 'Furniture,Beds & Accessories',
      },
      Technology: {
        Monitors: 'Baby & Toddler, Baby Safety',
      },
    },
    Move: {
      Travel: {
        'Prams / Strollers': 'Baby & Toddler, Baby Transport',
      },
      Accessories: {
        'Baby Carrier': 'Baby & Toddler, Baby Transport',
        Sling: 'Baby & Toddler, Baby Transport',
        'Stroller Organiser': 'Baby & Toddler, Baby Transport',
        'Stroller Straps': 'Baby & Toddler, Baby Transport',
        'Child Carriers': 'Baby & Toddler, Baby Transport',
        'Pram / Stroller Seat': 'Baby & Toddler, Baby Transport',
        'Pram Clips': 'Baby & Toddler, Baby Transport',
        'Sun Shades': 'Baby & Toddler, Baby Transport Accessories',
        'Car Seat': 'Baby & Toddler, Baby Transport Accessories',
        Isofix: 'Baby & Toddler, Baby Transport',
        Footmuff: 'Baby & Toddler, Baby Transport Accessories',
      },
      Car: {
        'Sun Shades': 'Baby & Toddler, Baby Transport Accessories',
      },
      'Kids Bags': {
        Backpacks: 'Luggage & Bags, Backpacks',
        'Pencil Cases': 'Luggage & Bags',
        Suitcases: 'Luggage & Bags, Suitcases',
      },
    },
    Parents: {
      Maternity: {
        Dresses: 'Clothing & Accessories, Clothing',
        Jumpsuits: 'Clothing & Accessories, Clothing',
        Tops: 'Clothing & Accessories, Clothing',
        Bottoms: 'Clothing & Accessories, Clothing',
        Cosmetics: 'Clothing & Accessories, Clothing',
        Sleepwear: 'Clothing & Accessories, Clothing',
        Balls: 'Sporting Goods, Exercise & Fitness',
        Accessories: 'Sporting Goods, Exercise & Fitness',
      },
      'Parent Bags': {
        'Changing Bags': 'Luggage & Bags, Backpacks',
        'Tote Bags': 'Luggage & Bags, Messenger Bags',
        Organisers: 'Luggage & Bags',
      },
      Welbeing: {
        Yoga: 'Sporting Goods, Exercise & Fitness',
        Pillows: 'Sporting Goods, Exercise & Fitness',
      },
    },
    Play: {
      'Toys - Push, Pull & Ride': {
        Walkers: 'Baby & Toddler, Baby Toys & Activity Equipment',
        Prams: 'Baby & Toddler, Baby Toys & Activity Equipment',
        Bikes: 'Baby & Toddler, Baby Toys & Activity Equipment',
      },
      'Baby Play': {
        'Play Gym': 'Baby & Toddler, Baby Toys & Activity Equipment',
        Rattlers: 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Soft Books': 'Toys & Games, Toys',
        Teethers: 'Baby & Toddler, Baby Health',
        Pacifiers: 'Toys & Games, Baby Health',
        Dummies: 'Toys & Games, Baby Health',
        Comforters: 'Toys & Games, Baby Health',
        Bouncers: 'Baby & Toddler, Baby Toys & Activity Equipment',
        Swings: 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Sensory Strips': 'Clothing & Accessories, Clothing',
        'Sensory Toys': 'Clothing & Accessories, Clothing',
        'Stacking Toys': 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Nesting Toys': 'Baby & Toddler, Baby Toys & Activity Equipment',
        Playmats: 'Baby & Toddler, Baby Toys & Activity Equipment',
      },
      'Playroom - Indoor': {
        'Tents and Teepees': 'Toys & Games, Baby Toys & Activity Equipment',
        Tents: 'Toys & Games, Baby Toys & Activity Equipment',
        Playmats: 'Baby & Toddler, Baby Toys & Activity Equipment',
        Beanbags: 'Baby & Toddler, Baby Toys & Activity Equipment',
        Pouffe: 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Sitting Balls': 'Baby & Toddler, Baby Toys & Activity Equipment',
        Chairs: 'Baby & Toddler, Baby Toys & Activity Equipment',
        Tables: 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Indoor Slides': 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Balance Boards': 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Soft Toys': 'Baby & Toddler, Baby Toys & Activity Equipment',
      },
      Activities: {
        'Books + Audio': 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Art & Crafts': 'Baby & Toddler, Baby Toys & Activity Equipment',
        Crayons: 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Educational Sets ': 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Flash Cards': 'Toys & Games, Toys',
        Puzzles: 'Toys & Games, Toys & Games',
      },
      Outdoor: {
        Bikes: 'Toys & Games, Outdoor Play Equipment',
        'Electric Bikes': 'Toys & Games, Outdoor Play Equipment',
        Trikes: 'Toys & Games, Outdoor Play Equipment',
        Scooters: 'Toys & Games, Outdoor Play Equipment',
        'Water Play': 'Toys & Games, Outdoor Play Equipment',
        Slides: 'Toys & Games, Outdoor Play Equipment',
        Trampolines: 'Toys & Games, Outdoor Play Equipment',
        Pools: 'Toys & Games, Outdoor Play Equipment',
        'Balance Boards': 'Toys & Games, Outdoor Play Equipment',
      },
      'Imaginative Play': {
        Kitchens: 'Toys & Games, Toys',
        Food: 'Toys & Games, Toys',
        'Role Play': 'Toys & Games, Toys',
        'Play Vehicles': 'Toys & Games, Toys',
        'Dolls House': 'Toys & Games, Toys',
        Dolls: 'Toys & Games, Toys',
      },
      Storage: {
        Toys: 'Furniture, Baby & Toddler Furniture',
        Baskets: 'Furniture, Baby & Toddler Furniture',
        Crates: 'Furniture, Baby & Toddler Furniture',
        Boxes: 'Furniture, Baby & Toddler Furniture',
      },
      'Wooden Toys': {
        Montesorri: 'Toys & Games, Baby Toys & Activity Equipment',
        'Stack & Build': 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Push & Pull': 'Toys & Games, Baby Toys & Activity Equipment',
        'Games & Puzzles': 'Toys & Games, Baby Toys & Activity Equipment',
        'Music & Audio': 'Toys & Games, Baby Toys & Activity Equipment',
        'Activity Cubes': 'Toys & Games, Baby Toys & Activity Equipment',
      },
      Party: {
        Plates: 'Arts & Entertainment, Party & Celebration',
        Cups: 'Arts & Entertainment, Party & Celebration',
        Napkins: 'Arts & Entertainment, Party & Celebration',
        'Party Bags': 'Arts & Entertainment, Party & Celebration',
      },
      Toys: {
        Mobiles: 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Stacking Toys': 'Baby & Toddler, Baby Toys & Activity Equipment',
        'Nesting Toys': 'Baby & Toddler, Baby Toys & Activity Equipment',
      },
    },
    Sleep: {
      Beds: {
        Cots: 'Furniture, Baby & Toddler Furniture',
        Cribs: 'Furniture, Baby & Toddler Furniture',
        'Moses Baskets': 'Furniture, Baby & Toddler Furniture',
        Matresses: 'Furniture, Baby & Toddler Furniture',
        'Sleep Pods': 'Furniture, Baby & Toddler Furniture',
      },
      Bedding: {
        'Sleeping Bags': 'Furniture, Baby & Toddler Furniture',
        Swaddles: 'Baby & Toddler, Swaddling & Receiving Blankets',
        'Sleep Bags': 'Furniture, Baby & Toddler Furniture',
        'Bed Linen': 'Furniture, Baby & Toddler Furniture',
        'Bed Sheets': 'Furniture, Baby & Toddler Furniture',
        'Blankets & Quilts': 'Baby & Toddler, Swaddling & Receiving Blankets',
        Pillows: 'Home & Garden, Linens & Bedding',
      },
      Support: {
        'Sleeping Aids': 'Health & Beauty, Personal Care',
        'White Noise Machines': 'Health & Beauty, Personal Care',
        'Baby Monitors': 'Baby & Toddler, Baby Safety',
        Thermometers: 'Baby & Toddler, Baby Safety',
        'Night Lights': 'Baby & Toddler, Baby Safety',
        Mobiles: 'Baby & Toddler, Baby Toys & Activity Equipment',
      },
    },
    Wear: {
      'All in Ones': {
        Rompers: 'Clothing & Accessories, Clothing',
        Dungarees: 'Clothing & Accessories, Clothing',
        Jumpsuits: 'Clothing & Accessories, Clothing',
        'Boiler Suits': 'Clothing & Accessories, Clothing',
      },
      Nightwear: {
        Pyjamas: 'Clothing & Accessories, Clothing',
        'Sleepsuit ': 'Clothing & Accessories, Clothing',
        Onesie: 'Clothing & Accessories, Clothing',
        'Dressing Gown': 'Clothing & Accessories, Clothing',
        Vests: 'Clothing & Accessories, Clothing',
      },
      Outerwear: {
        Coats: 'Clothing & Accessories, Clothing',
        Waterproofs: 'Clothing & Accessories, Clothing',
        Pramsuit: 'Clothing & Accessories, Clothing',
        Puddlesuit: 'Clothing & Accessories, Clothing',
        Snowsuit: 'Clothing & Accessories, Clothing',
        Ponchos: 'Clothing & Accessories, Clothing',
        Jacket: 'Clothing & Accessories, Clothing',
      },
      Bottoms: {
        Shorts: 'Clothing & Accessories, Clothing',
        Leggings: 'Clothing & Accessories, Clothing',
        Joggers: 'Clothing & Accessories, Clothing',
        Trousers: 'Clothing & Accessories, Clothing',
      },
      Knitwear: {
        Jumpers: 'Clothing & Accessories, Clothing',
        Cardigan: 'Clothing & Accessories, Clothing',
        Knitwear: 'Clothing & Accessories, Clothing',
      },
      Tops: {
        Vests: 'Clothing & Accessories, Clothing',
        Bodysuits: 'Clothing & Accessories, Clothing',
        'T-Shirts': 'Clothing & Accessories, Clothing',
        Hoodies: 'Clothing & Accessories, Clothing',
        Jumpers: 'Clothing & Accessories, Clothing',
        Shirts: 'Clothing & Accessories, Clothing',
        Sweaters: 'Clothing & Accessories, Clothing',
        Blouse: 'Clothing & Accessories, Clothing',
      },
      'Dresses & Skirts': {
        Skirts: 'Clothing & Accessories, Clothing',
        Dresses: 'Clothing & Accessories, Clothing',
      },
      Accessories: {
        Hats: 'Clothing & Accessories, Clothing',
        Mittens: 'Clothing & Accessories, Clothing',
        Cape: 'Clothing & Accessories, Clothing',
        Socks: 'Clothing & Accessories, Clothing',
        Scarves: 'Clothing & Accessories, Clothing',
        Scrunchies: 'Clothing & Accessories, Clothing',
        Sunglasses: 'Clothing & Accessories, Clothing',
      },
      Swimwear: {
        'Swimming Costume': 'Clothing & Accessories, Clothing',
        Wetsuit: 'Clothing & Accessories, Clothing',
        'Swimming Shorts': 'Clothing & Accessories, Clothing',
        'Swim Suit': 'Clothing & Accessories, Clothing',
        Bikini: 'Clothing & Accessories, Clothing',
        Pants: 'Clothing & Accessories, Clothing',
        'Vest ': 'Clothing & Accessories, Clothing',
        Shorts: 'Clothing & Accessories, Clothing',
      },
      Footwear: {
        Sandals: 'Clothing & Accessories, Shoes',
        Shoes: 'Clothing & Accessories, Shoes',
        Trainers: 'Clothing & Accessories, Shoes',
        Wellingtons: 'Clothing & Accessories, Shoes',
        Boots: 'Clothing & Accessories, Clothing',
      },
    },
    Gifts: {
      'Gifts for parents': {
        'Gifts under £25': '',
        'Gifts £25-£50': '',
        'Gifts under £100': '',
        'Cards & Gift Wrap': '',
      },
      'Gifts for toddlers': {
        'Gifts under £25': 'Baby & Toddler',
        'Gifts £25-£50': 'Baby & Toddler',
        'Gifts under £100': 'Baby & Toddler',
        'Cards & Gift Wrap': 'Baby & Toddler',
      },
      'Gifts for babies': {
        'Gifts under £25': 'Baby & Toddler, Baby Gift Sets',
        'Gifts £25-£50': 'Baby & Toddler, Baby Gift Sets',
        'Gifts under £100': 'Baby & Toddler, Baby Gift Sets',
        'Cards & Gift Wrap': 'Baby & Toddler, Baby Gift Sets',
      },
      'Gifts for tweens & teens': {
        'Gifts under £25': '',
        'Gifts £25-£50': '',
        'Gifts under £100': '',
        'Cards & Gift Wrap': '',
      },
      Accessories: {
        Announcements: '',
        Christmas: '',
        'Bags & Boxes': '',
      },
    },
  },
};
